---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Self-Hosted Homepage
description: A self-hosted homepage for your browser.

background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm
  opacity: 30
color: slate
theme: dark

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: duckduckgo # google, duckduckgo, bing, baidu, brave or custom
